### ISSUE TITLE
Window top corners don't look fine when tiled

### ISSUE THREAD

**Issue by ding0z** [CoolAller/WhiteSur-gtk-theme-cinnamon#1]
Virtual Machine on Parallels VM.
Linux Mint 22.

The window usually looks fine unless snapped on the right or left of the screen.
![Screenshot 2024-08-09 at 13 57 57](https://github.com/user-attachments/assets/a6514c7f-36ab-4f42-bd54-a13593c000e1)

**Comment by CoolAller** [comment]
Ok, I'll take a look.

**Comment by CoolAller** [comment]
I fixed it, please check. 
After changing the theme, you need to Log Out or run the command in the terminal (Cinnamon will be restarted): 
`nohup cinnamon --replace > /dev/null 2>&1 &`

**Comment by ding0z** [comment]
Superb! Many thanks for the fix.

**Comment by CoolAller** [comment]
You are welcome!

**Comment by CoolAller** [comment]
You are welcome!
